### ISSUE TITLE
Auto format to select compression choice for output

### ISSUE THREAD

**Issue by khyox** [rrwick/Porechop#13]
Hello Ryan,

First of all, thank you very much for Porechop, it is fabulous! I am using it with custom barcoding in `adapters.py` and my first testings are promising.

This is more a feature request, but I would expect to have an uncompressed output if the input is uncompressed, specially with the `auto` choice for the `format` flag. Another option is to extend the choices to something like `{auto,fasta,fastq,fastagz,fastqgz}` and avoid forced gzipping the output. Whatever... this is just a suggestion and a good excuse to thank you for Porechop.

**Comment by rrwick** [comment]
That's a good idea, and since I've been working on Porechop recently, I decided to quickly implement this while the code's still fresh in my head.

I think it's all working now on the master branch. The format option are pretty much as you suggested, but I put a dot in the gzipped ones:
`{auto,fasta,fastq,fasta.gz,fastq.gz}`

Give it a try and let me know if anything's not right!

**Comment by khyox** [comment]
Tried and all running smoothly! Thank you very much Ryan!
