### ISSUE TITLE
Low barcode assignment %

### ISSUE THREAD

**Issue by cmaggior** [rrwick/Porechop#25]
Hello,

I'm trying to run a fasta file produced from the SQK-RLB001 kit and am getting nearly half of my sequences in the 'none' file, even after lowering the barcode threshold to 20. Is this something other users have experienced? I know MinION data isn't exactly error-free. Have the barcodes in the known adapters been updated to the new kit releases?

My apologies if this is a silly question. Thanks for making a great open source program, Ryan!

- Catherine

**Comment by rrwick** [comment]
Hi Catherine,

It is often a challenge to get _all_ of the _actual_ adapter sequences from Oxford Nanopore, but since they seem to use the same barcode sequences in each kit, I suspect Porechop would be compatible with SQK-RLB001.

Half of the reads being unclassified doesn't sound too crazy to me. I've seen about 1/3 in the past. Another setting which might help is `--barcode_diff`. The default is 5, which means the bet barcode identity must be 5 better than the second best, or else the read is too-close-to-call and is unclassified. You could try a very lenient `--barcode_diff 1` to see if that helps.

Also as a sanity check - see what Albacore does. If you basecall the reads with Albacore's `--barcoding` option, how many does it fail to classify? In my experience Porechop's default settings are a bit more strict, so I'd expect Albacore to classify a bit more. But if they are in the same ballpark, then I can feel confident that Porechop's not doing anything terribly wrong.

Let me know how you go!
Ryan

**Comment by cmaggior** [comment]
Hi Ryan,

Thanks so much for your response! I'll give lowering the --barcode_diff
threshold a shot.

For what it's worth, basecalling with Albacore produced pretty much the
same amount of reads classified, so I'm sure it's not Porechop that's the
problem. I've had issues with MinION data in the past, but this is the
first time I've used their barcoding kits, so I wasn't sure what was
standard for users.

Thanks again, and I'll let you know how --barcode_diff <5 goes.

- Catherine

**Comment by rrwick** [comment]
Sounds good - thanks!
